BeerCatalogue/BeerCatalogueApp.Web/Models/BeerViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace BeerCatalogueApp.Web.Models
{
    public class BeerViewModel
    {

        public int Id { get; set; }
        [Required]
        [StringLength(30,MinimumLength = 3,ErrorMessage = "Beer name should be between 3 and 30 characters")]
        public string Name { get; set; }
        public string Description { get; set; }

        public string ImageURL
        {
            get
            {
                return $"~/images/{this.Name}.jpg";
            }
        }
        [Required]
        public string ABV { get; set; }
        [Required]
        public float Milliters { get; set; }
        public int BreweryId { get; set; }
        public double Rating { get; set; }
        public string BreweryName { get; set; }
        public string StyleName { get; set; }
        public int StyleId { get; set; }
        public ICollection<ReviewViewModel> Reviews { get; set; } = new List<ReviewViewModel>();
        public ICollection<BeerRatingViewModel> BeerRatings { get; set; } = new List<BeerRatingViewModel>();
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Controllers/BeersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerCatalogue.Database;
using BeerCatalogue.Services.Contracts;
using BeerCatalogueApp.Web.Models;
using BeerCatalogue.Services.DTOsEntities;
using BeerCatalogueApp.Web.VMMapper;
using BeerCatalogueApp.Web.VMMapper.Contracts;
using Microsoft.AspNetCore.Routing;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Authorization;

namespace BeerCatalogueApp.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly BeerCatalogueContext _context;
        private readonly IVMMapper<BeerDTO, BeerViewModel> beerMapper;

        public BeersController(IBeerService beerService, BeerCatalogueContext _context, IVMMapper<BeerDTO, BeerViewModel> beerMapper)
        {
            this.beerService = beerService;
            this._context = _context;
            this.beerMapper = beerMapper;
        }

        public async Task<IActionResult> Index(string filter, int page = 1, string sortExpression = "Name")
        {
            var beerContext = await this.beerService.GetBeers();

            if (!String.IsNullOrWhiteSpace(filter))
            {
                beerContext = beerContext.Where(b => b.Name.ToLower().Contains(filter));
            }
            
            var beersViewModel = beerContext.Select(b => this.beerMapper.MapFromDTOToVM(b));
            
            var beers = PagingList.Create(beersViewModel, 4, page, sortExpression, "Name");

            beers.RouteValue = new RouteValueDictionary
            {
                {"filter", filter }
            };

            return View(beers);
        }
        public async Task<IActionResult> Details(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }
            
            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // GET: Beers/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["BreweryName"] = new SelectList(_context.Breweries, "Name", "Name");
            ViewData["StyleName"] = new SelectList(_context.Styles, "Name", "Name");
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ABV,Milliters,BreweryId,BreweryName,StyleId,StyleName,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.CreateBeer(beer);

                return RedirectToAction(nameof(Index));
            }
            return View(beer);
        }

        // GET: Beers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerModel = beer.GetView();
            return View(beerModel);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ABV,Milliters,BreweryId,StyleId,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.UpdateBeer(id, beer);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // POST: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.beerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> FilterByCountry(int id)
        {
            var countryName = this._context.Countries.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("country", countryName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
        public async Task<IActionResult> FilterByStyle(int id)
        {
            var styleName = this._context.Styles.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("style", styleName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Controllers/ReviewsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BeerCatalogue.Database;
using BeerCatalogue.Models;
using Microsoft.AspNetCore.Authorization;
using BeerCatalogue.Services.DTOsEntities;
using Microsoft.AspNetCore.Identity;
using BeerCatalogue.Services.Contracts;
using BeerCatalogueApp.Web.VMMapper;

namespace BeerCatalogueApp.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewService reviewService;
        private readonly UserManager<User> userManager;
        private readonly BeerCatalogueContext _context;

        public ReviewsController(UserManager<User> userManager, IReviewService reviewService, BeerCatalogueContext context)
        {
            this.reviewService = reviewService;
            this.userManager = userManager;
            this._context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index(int id)
        {
            var reviewsDTO = await reviewService.GetAllReviews(id);
            var reviews = reviewsDTO.Select(x => x.GetViem());
            return View(reviews);
        }

        [Authorize]
        public async Task<IActionResult> UserReviews()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var reviewDTO = await reviewService.GetReviewsForUser(user.Id);
            var reviews = reviewDTO.Select(x => x.GetViem());
            return View(reviews);
        }
        [Authorize]
        // GET: Reviews/Create
        public IActionResult Create(int id)
        {
            TempData["BeerName"] = this._context.Beers.FirstOrDefaultAsync(b => b.Id == id).Result.Name;
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Comment,BeerId,UserId,BeerName,Username")] ReviewDTO review)
        {

            var name = TempData["BeerName"].ToString();
            var user = await this.userManager.GetUserAsync(this.User);
            review.Username = user.UserName;
            review.BeerName = name;
            try
            {
                if (ModelState.IsValid)
                {
                    await reviewService.Create(review);
                    return RedirectToAction("Index", "Beers");
                }
            }
            catch
            {
                ViewBag.Message = "You already made a review for this beer,check your reviews for more info";
                return View();
            }
            return View(review);
        }

        [Authorize]
        public async Task<IActionResult> Remove(int beerId,int userId)
        {
            var result = await this.reviewService.Delete(beerId, userId);

            if (result == false)
            {
                return BadRequest();
            }

            return RedirectToAction("Index","Beers");

        }
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/Create.cshtml
@model BeerViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Beer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ABV" class="control-label"></label>
                <input asp-for="ABV" class="form-control" />
                <span asp-validation-for="ABV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Milliters" class="control-label"></label>
                <input asp-for="Milliters" class="form-control" />
                <span asp-validation-for="Milliters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreweryName" class="control-label"></label>
                <select asp-for="BreweryName" class="form-control" asp-items="ViewBag.BreweryName"></select>
            </div>
            <div class="form-group">
                <label asp-for="StyleName" class="control-label"></label>
                <select asp-for="StyleName" class="form-control" asp-items="ViewBag.StyleName"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/Delete.cshtml
@model BeerViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Beer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/Details.cshtml
@model BeerViewModel
@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mb-4">@Model.Name</h1>

<div class="card mb-3">
    <div class="row no-gutters w-100">
        <div class="col-md-4">
            <img src="@Url.Content(Model.ImageURL)" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <p class="card-text"><strong>Description:</strong> @Model.Description</p>
                <p class="card-text"><strong>ABV:</strong> @Model.ABV</p>
                <p class="card-text"><strong>Mililiters:</strong> @Model.Milliters</p>
                <p class="card-text"><strong>Brewery:</strong> @Model.BreweryName</p>
                <p class="card-text"><strong>Style:</strong> @Model.StyleName</p>
                <p class="card-text"><strong>Rating:</strong> @Model.Rating</></p>
            </div>
        </div>
    </div>
</div>

<div>
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-dark">Edit</a>
    }
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>

    @if (SignInManager.IsSignedIn(User))
    {
        <a asp-controller="BeerRatings" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-warning">Rate a beer</a>
        <form asp-controller="Wishlists" asp-action="Add" asp-route-id="@Model.Id" class="d-inline-block">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Add to wishlist" class="btn btn-primary my-1" />
        </form>
        <form asp-controller="Dranklists" asp-action="Add" asp-route-id="@Model.Id" class="d-inline-block">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Add to dranklist" class="btn btn-primary my-1" />
        </form>
        <a asp-controller="Reviews" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-dark my-1">Add review</a>
    }
    <form asp-controller="Reviews" asp-action="Index" asp-route-id="@Model.Id" class="d-inline-block">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="See all reviews" class="btn btn-primary my-1" />
    </form>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/Edit.cshtml
@model BeerViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Beer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ABV" class="control-label"></label>
                <input asp-for="ABV" class="form-control" />
                <span asp-validation-for="ABV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Milliters" class="control-label"></label>
                <input asp-for="Milliters" class="form-control" />
                <span asp-validation-for="Milliters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/FilterByCountry.cshtml
@model IEnumerable<BeerViewModel>

@{
    ViewData["Title"] = "FilterByCountry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-block w-100 float-left position-relative mb-4">
    <h1 class="text-left float-left my-4 text-left w-75 d-inline-block">Beers</h1>
    <p class="text-right float-right w-25 d-inline-block align-middle" style="position: absolute; top: 35%;">
    </p>
</div>
<div class="container p-0">
    <div class="row d-flex">
        @foreach (var item in Model)
        {
            <partial name="_SingleBeerPartial" model="item" />
        }
    </div>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/FilterByStyle.cshtml
@model IEnumerable<BeerViewModel>

@{
    ViewData["Title"] = "FilterByStyle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-block w-100 float-left position-relative mb-4">
    <h1 class="text-left float-left my-4 text-left w-75 d-inline-block">Beers</h1>
    <p class="text-right float-right w-25 d-inline-block align-middle" style="position: absolute; top: 35%;">
    </p>
</div>
<div class="container p-0">
    <div class="row d-flex">
        @foreach (var item in Model)
        {
            <partial name="_SingleBeerPartial" model="item" />
        }
    </div>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Beers/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<BeerViewModel>
@using ReflectionIT.Mvc.Paging

@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject SignInManager<User> SignInManager
@addTagHelper *, ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="get" class="form-inline my-2 my-lg-0">
    <input name="filter" class="form-control mr-sm-2" placeholder="Search for beer"
           value="@Model.RouteValue["Filter"]" />
    <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">
        <span aria-hidden="true"></span> Search
    </button>
</form>
<div class="d-block w-100 float-left position-relative mb-4">
    <h1 class="text-left float-left my-4 text-left w-75 d-inline-block">Beers</h1>
    <p class="text-right float-right w-25 d-inline-block align-middle" style="position: absolute; top: 35%;">
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
</div>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>
                @Html.SortableHeaderFor(model => model.Name)
            </th>
            <th>
                @Html.SortableHeaderFor(model => model.ABV)
            </th>
            <th>
                @Html.SortableHeaderFor(model => model.Rating)
            </th>
        </tr>
    </thead>
</table>
<div class="container p-0">
    <div class="row d-flex">
        @foreach (var item in Model)
        {
            <partial name="_SingleBeerPartial" model="item" />
        }
    </div>
</div>


<nav aria-label="Page navigation example">
    <vc:pager paging-list="@Model" />
</nav>