BeerCatalogue/BeerCatalogueApp.Web/Controllers/BeersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerCatalogue.Database;
using BeerCatalogue.Services.Contracts;
using BeerCatalogueApp.Web.Models;
using BeerCatalogue.Services.DTOsEntities;
using BeerCatalogueApp.Web.VMMapper;
using BeerCatalogueApp.Web.VMMapper.Contracts;
using Microsoft.AspNetCore.Routing;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Authorization;

namespace BeerCatalogueApp.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly BeerCatalogueContext _context;
        private readonly IVMMapper<BeerDTO, BeerViewModel> beerMapper;

        public BeersController(IBeerService beerService, BeerCatalogueContext _context, IVMMapper<BeerDTO, BeerViewModel> beerMapper)
        {
            this.beerService = beerService;
            this._context = _context;
            this.beerMapper = beerMapper;
        }

        public async Task<IActionResult> Index(string filter, int page = 1, string sortExpression = "Name")
        {
            var beerContext = await this.beerService.GetBeers();

            if (!String.IsNullOrWhiteSpace(filter))
            {
                beerContext = beerContext.Where(b => b.Name.ToLower().Contains(filter));
            }
            
            var beersViewModel = beerContext.Select(b => this.beerMapper.MapFromDTOToVM(b));
            
            var beers = PagingList.Create(beersViewModel, 4, page, sortExpression, "Name");

            beers.RouteValue = new RouteValueDictionary
            {
                {"filter", filter }
            };

            return View(beers);
        }
        public async Task<IActionResult> Details(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }
            
            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // GET: Beers/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["BreweryName"] = new SelectList(_context.Breweries, "Name", "Name");
            ViewData["StyleName"] = new SelectList(_context.Styles, "Name", "Name");
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ABV,Milliters,BreweryId,BreweryName,StyleId,StyleName,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.CreateBeer(beer);

                return RedirectToAction(nameof(Index));
            }
            return View(beer);
        }

        // GET: Beers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerModel = beer.GetView();
            return View(beerModel);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ABV,Milliters,BreweryId,StyleId,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.UpdateBeer(id, beer);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // POST: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.beerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> FilterByCountry(int id)
        {
            var countryName = this._context.Countries.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("country", countryName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
        public async Task<IActionResult> FilterByStyle(int id)
        {
            var styleName = this._context.Styles.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("style", styleName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Controllers/StylesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BeerCatalogue.Services.Contracts;
using BeerCatalogue.Services.DTOsEntities;
using BeerCatalogueApp.Web.VMMapper;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;

namespace BeerCatalogueApp.Web.Controllers
{
    public class StylesController : Controller
    {
        private readonly IStyleService styleService;

        public StylesController(IStyleService styleService)
        {
            this.styleService = styleService;
        }

        // GET: Styles
        public async Task<IActionResult> Index(int page, string sortExpression = "Name")
        {
            var styles = await styleService.GetAllStyles();

            var result = styles.Select(x => x.GetViem());

            var stylesPaging = PagingList.Create(result, 4, page, sortExpression, "Name");

            return View(stylesPaging);
        }

        // GET: Styles/Details/5
        public async Task<IActionResult> Details(int id)
        {
            StyleDTO style;

            try
            {
                style = await styleService.GetStyle(id);
            }
            catch (System.Exception)
            {
                return NotFound();
            }

            var styleModel = style.GetViem();
            return View(styleModel);
        }

        // GET: Styles/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] StyleDTO style)
        {
            if (ModelState.IsValid)
            {
                var styleDTO = await styleService.CreateStyle(style);

                return RedirectToAction(nameof(Index));
            }
            return View(style);
        }
        // GET: Styles/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            StyleDTO style;

            try
            {
                style = await styleService.GetStyle(id);
            }
            catch (System.Exception)
            {
                return NotFound();
            }

            var styleModel = style.GetViem();
            return View(styleModel);
        }
        // POST: Styles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] StyleDTO style)
        {
            if (id != style.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await styleService.UpdateStyle(id, style);
                return RedirectToAction(nameof(Index));
            }
            return View(style);
        }

        // GET: Styles/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            StyleDTO style;

            try
            {
                style = await styleService.GetStyle(id);
            }
            catch (System.Exception)
            {
                return NotFound();
            }

            var styleView = style.GetViem();
            return View(styleView);
        }

        // POST: Styles/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.styleService.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        //private bool StyleExists(int id)
        //{
        //    return _context.Styles.Any(e => e.Id == id);
        //}
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1 class="my-5 text-center">@ViewBag.ErrorMessage</h1>

<a asp-action="Index" asp-controller="Home">
    <h5 class="text-center">Click here to navigate to the home page</h5>
</a>

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerCatalogueApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/beerIcon.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    Beer Catalogue
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Styles" asp-action="Index">Styles</a>
                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Index">Beers</a>
                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Index">Breweries</a>
                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wishlists" asp-action="Index">Wishlist</a>
                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dranklists" asp-action="Index">Dranklist</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BeerCatalogue
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/_SingleBeerPartial.cshtml
@model BeerViewModel
@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject UserManager<User> UserManager

<div class="col-md-3 mb-5">
    <div class="card text-center">
        <img src="@Url.Content(Model.ImageURL)" height="280" class="card-img-top" alt="" />
        <div class="card-body">
            <h5 class="card-title pt-2" style="height:55px">@Model.Name</h5>
            <a asp-area="" asp-controller="Beers" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-info d-block w-100 my-3">More Details</a>
            @if (User.IsInRole("Admin"))
            {
                <a asp-area="" asp-controller="Beers" asp-action="Edit" asp-route-id="@Model.Id" class="float-left btn btn-dark" style="width:45%">Edit</a>
                <a asp-area="" asp-controller="Beers" asp-action="Delete" asp-route-id="@Model.Id" class="float-right btn btn-danger" style="width:45%;">Delete</a>
            }
        </div>
    </div>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/_SingleBreweryPartial.cshtml
@model BreweryViewModel
@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject UserManager<User> UserManager
<div class="col-md-3 mb-5">
    <div class="card text-center">
        <img src="~/images/bulgariaFlag.jpg" class="card-img-top" alt="" />
        <div class="card-body">
            <h5 class="card-title" style="height:55px">@Model.Name</h5>
            <a asp-area="" asp-controller="Breweries" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary d-block w-100 my-3">More Details</a>

            @if (User.IsInRole("Admin"))
            {
                <a asp-area="" asp-controller="Breweries" asp-action="Edit" asp-route-id="@Model.Id" class="float-left btn btn-warning" style="width:45%">Edit</a>
                <a asp-area="" asp-controller="Breweries" asp-action="Delete" asp-route-id="@Model.Id" class="float-right btn btn-danger" style="width:45%;">Delete</a>
            }
        </div>
    </div>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/_SingleCountryPartial.cshtml
@model CountryViewModel
@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject UserManager<User> UserManager
<div class="col-md-3 mb-5">
    <div class="card text-center">
        <img src="@Url.Content(Model.ImageURL)" class="card-img-top" alt="" />
        <div class="card-body">
            <h5 class="card-title pt-2" style="height:55px">@Model.Name</h5>
            <a asp-area="" asp-controller="Countries" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary d-block w-100 my-3">More Details</a>
            @*<a asp-area="" asp-controller="Beers" asp-action="FilterByCountry" asp-route-id="@Model.Id" class="btn btn-dark d-block w-100 my-3">Get all beers for country</a>*@

            @if (User.IsInRole("Admin"))
            {
                <a asp-area="" asp-controller="Countries" asp-action="Edit" asp-route-id="@Model.Id" class="float-left btn btn-warning" style="width:45%">Edit</a>
                <a asp-area="" asp-controller="Countries" asp-action="Delete" asp-route-id="@Model.Id" class="float-right btn btn-danger" style="width:45%">Delete</a>
            }
        </div>
    </div>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Shared/_SingleStylePartial.cshtml
@model StyleViewModel
<div class="col-md-3 mb-5">
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title pt-2" style="height:55px">@Model.Name</h5>
            <a asp-area="" asp-controller="Styles" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary d-block w-100 my-3">More Details</a>
        </div>
    </div>
</div>