BeerCatalogue/BeerCatalogueApp.Web/Models/CountryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace BeerCatalogueApp.Web.Models
{
    public class CountryViewModel
    {
        [JsonIgnore]
        public int Id { get; set; }

        [Required(ErrorMessage = "Country name is required")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Country name should be between 3 and 60 symbols")]
        public string Name { get; set; }

        public string ImageURL
        {
            get
            {
                return $"~/images/{this.Name}.jpg";
            }
        }

        public ICollection<BreweryViewModel> Breweries { get; set; } = new List<BreweryViewModel>();
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Controllers/BeersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerCatalogue.Database;
using BeerCatalogue.Services.Contracts;
using BeerCatalogueApp.Web.Models;
using BeerCatalogue.Services.DTOsEntities;
using BeerCatalogueApp.Web.VMMapper;
using BeerCatalogueApp.Web.VMMapper.Contracts;
using Microsoft.AspNetCore.Routing;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Authorization;

namespace BeerCatalogueApp.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly BeerCatalogueContext _context;
        private readonly IVMMapper<BeerDTO, BeerViewModel> beerMapper;

        public BeersController(IBeerService beerService, BeerCatalogueContext _context, IVMMapper<BeerDTO, BeerViewModel> beerMapper)
        {
            this.beerService = beerService;
            this._context = _context;
            this.beerMapper = beerMapper;
        }

        public async Task<IActionResult> Index(string filter, int page = 1, string sortExpression = "Name")
        {
            var beerContext = await this.beerService.GetBeers();

            if (!String.IsNullOrWhiteSpace(filter))
            {
                beerContext = beerContext.Where(b => b.Name.ToLower().Contains(filter));
            }
            
            var beersViewModel = beerContext.Select(b => this.beerMapper.MapFromDTOToVM(b));
            
            var beers = PagingList.Create(beersViewModel, 4, page, sortExpression, "Name");

            beers.RouteValue = new RouteValueDictionary
            {
                {"filter", filter }
            };

            return View(beers);
        }
        public async Task<IActionResult> Details(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }
            
            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // GET: Beers/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["BreweryName"] = new SelectList(_context.Breweries, "Name", "Name");
            ViewData["StyleName"] = new SelectList(_context.Styles, "Name", "Name");
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ABV,Milliters,BreweryId,BreweryName,StyleId,StyleName,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.CreateBeer(beer);

                return RedirectToAction(nameof(Index));
            }
            return View(beer);
        }

        // GET: Beers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerModel = beer.GetView();
            return View(beerModel);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ABV,Milliters,BreweryId,StyleId,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                await this.beerService.UpdateBeer(id, beer);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            BeerDTO beer;

            try
            {
                beer = await beerService.GetBeer(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var beerMod = beer.GetView();
            return View(beerMod);
        }

        // POST: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.beerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> FilterByCountry(int id)
        {
            var countryName = this._context.Countries.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("country", countryName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
        public async Task<IActionResult> FilterByStyle(int id)
        {
            var styleName = this._context.Styles.FirstOrDefaultAsync(s => s.Id == id).Result.Name;
            //TODO: not complete at all
            var beers = await this.beerService.Filter("style", styleName);

            var br = beers.Select(x => x.GetView());
            return View(br);
        }
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Controllers/CountriesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BeerCatalogue.Database;
using BeerCatalogue.Services.Contracts;
using BeerCatalogueApp.Web.VMMapper.Contracts;
using BeerCatalogue.Services.DTOsEntities;
using BeerCatalogueApp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;

namespace BeerCatalogueApp.Web.Controllers
{
    public class CountriesController : Controller
    {
        private readonly BeerCatalogueContext _context;
        private readonly ICountryService countryService;
        private readonly IVMMapper<CountryDTO, CountryViewModel> mapper;

        public CountriesController(BeerCatalogueContext context, ICountryService countryService,
            IVMMapper<CountryDTO, CountryViewModel> mapper)
        {
            _context = context;
            this.countryService = countryService;
            this.mapper = mapper;
        }

        // GET: Countries
        public async Task<IActionResult> Index(int page = 1, string sortExpression = "Name")
        {
            var countries = await this.countryService.GetAllCountries();

            var countriesViewModels = countries.Select(countries => this.mapper.MapFromDTOToVM(countries));

            var countriesPaging = PagingList.Create(countriesViewModels, 4, page, sortExpression, "Name");

            return View(countriesPaging);
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int id)
        {
            CountryDTO country;

            try
            {
                country = await this.countryService.GetCountry(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var countryViewModel = this.mapper.MapFromDTOToVM(country);

            return View(countryViewModel);
        }

        // GET: Countries/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] CountryViewModel country)
        {
            if (ModelState.IsValid)
            {
                var countryDTO = this.mapper.MapFromVMToDTO(country);

                await this.countryService.Create(countryDTO);

                return RedirectToAction(nameof(Index));
            }

            return View(country);
        }

        // GET: Countries/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            CountryDTO country;

            try
            {
                country = await this.countryService.GetCountry(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var countryViewModel = this.mapper.MapFromDTOToVM(country);

            return View(countryViewModel);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] CountryViewModel country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var countryDTO = this.mapper.MapFromVMToDTO(country);

                    await this.countryService.Update(id, countryDTO);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            CountryDTO country;

            try
            {
                country = await this.countryService.GetCountry(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            var countryViewModel = this.mapper.MapFromDTOToVM(country);

            return View(countryViewModel);
        }
        //TODO: CHECK FOR DELETED COUNTRIES
        // POST: Countries/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.countryService.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(int id)
        {
            return _context.Countries.Any(e => e.Id == id);
        }
    }
}

BeerCatalogue/BeerCatalogueApp.Web/Views/Countries/Create.cshtml
@model CountryViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

BeerCatalogue/BeerCatalogueApp.Web/Views/Countries/Delete.cshtml
@model CountryViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Countries/Details.cshtml
@model CountryViewModel
@using Microsoft.AspNetCore.Identity
@using BeerCatalogue.Models

@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h1>Country</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>

<div class="mb-1">
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="Countries" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
        <a asp-controller="Countries" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
    }
</div>

<div>
    <a asp-controller="Breweries" asp-action="GetBreweriesForCountry" asp-route-id="@Model.Id" class="btn btn-primary">Breweries in @Model.Name</a>
    <a asp-controller="Beers" asp-action="FilterByCountry" asp-route-id="@Model.Id" class="btn btn-primary ">Beers brewed in @Model.Name</a>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Countries/Edit.cshtml
@model CountryViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BeerCatalogue/BeerCatalogueApp.Web/Views/Countries/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<CountryViewModel>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-block w-100 float-left position-relative mb-4">
    <h1 class="text-left float-left my-4 text-left w-75 d-inline-block">Countries</h1>
    <p class="text-right float-right w-25 d-inline-block align-middle" style="position: absolute; top: 35%;">
        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-primary" asp-action="Create">Create New</a>
        }
    </p>

</div>

<table class="table table-striped">
    <thead>
    <tr>
        <th>
            @Html.SortableHeaderFor(model => model.Name)
        </th>
    </tr>
    </thead>
</table>

<div class="container p-0">
    <div class="row d-flex">
        @foreach (var item in Model)
        {
            <partial name="_SingleCountryPartial" model="item"/>
        }
    </div>
</div>

<nav aria-label="Page navigation example">
    <vc:pager paging-list="@Model" />
</nav>